In [2]:
a,b = 0,1
for i in range(15):
    print(a)
    a,b = b,a+b

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377

In [11]:
t = 51
for i in range(2,t):
    if t % i == 0:
        print("no prime",end=" ")
        break
else:
    print("prime",end=" ")
if t % 3 == 0 and t % 5 == 0:
    print("fizz buzz")
elif t % 3 == 0:
    print("fizz")
elif t % 5 == 0:
    print("buzz")

no prime fizz

In [24]:
def prime(n):
    for i in range(2,n):
        if n % i == 0:
            return "No prime"
    return "Prime"

def fb(n):
    if n % 3 ==0 and n % 5 == 0:
        return "fizz-buzz"
    elif n % 3 ==0:
        return "fizz"
    elif n % 5 == 0:
        return "buzz"
    else:
        return ""
    
# n = int(input("Number ?"))

# print(prime(n),fb(n))

res = []

nl = [1,2,3,4,5,6,7,8,9,10]

for i in nl:
    res.append(str(prime(i))+" "+str(fb(i)))
res

['Prime ',
 'Prime ',
 'Prime fizz',
 'No prime ',
 'Prime buzz',
 'No prime fizz',
 'Prime ',
 'No prime ',
 'No prime fizz',
 'No prime buzz']

In [30]:
import pandas as pd

In [31]:
df = pd.read_csv('sales_data.csv')

In [33]:
df.head()

,OrderID,OrderDate,Region,Product,Quantity,UnitPrice,CustomerSegment,Discount,ShippingCost,DeliveryDate
0,1001,2023-01-05,East,Laptop,1,1200.0,Consumer,0.05,25.0,2023-01-08
1,1002,2023-01-06,West,Mouse,3,25.5,Corporate,0.10,5.0,2023-01-10
2,1003,2023-01-07,Central,Keyboard,2,75.0,Home Office,0.00,10.0,2023-01-11
3,1004,2023-01-08,East,Monitor,1,300.0,Consumer,0.05,15.0,2023-01-12
4,1005,2023-01-09,South,Webcam,5,35.0,Corporate,0.15,7.5,2023-01-14

In [34]:
df.tail()

,OrderID,OrderDate,Region,Product,Quantity,UnitPrice,CustomerSegment,Discount,ShippingCost,DeliveryDate
20,1021,2023-01-25,South,Laptop,1,1200.0,Home Office,0.00,25.0,2023-01-29
21,1022,2023-01-26,East,Mouse,3,25.5,Consumer,0.05,5.0,2023-01-30
22,1023,2023-01-27,West,Keyboard,2,75.0,Corporate,0.10,10.0,2023-01-31
23,1024,2023-01-28,Central,Monitor,1,300.0,Home Office,0.00,15.0,2023-02-01
24,1025,2023-01-29,South,Webcam,5,35.0,Consumer,0.05,7.5,2023-02-02

In [36]:
df.describe()

           OrderID   Quantity   UnitPrice   Discount  ShippingCost
count    25.000000  25.000000    25.00000  25.000000     25.000000
mean   1013.000000   2.160000   327.10000   0.054000     14.100000
std       7.359801   1.280625   457.01208   0.047697     10.677078
min    1001.000000   1.000000    25.50000   0.000000      5.000000
25%    1007.000000   1.000000    35.00000   0.000000      7.500000
50%    1013.000000   2.000000    75.00000   0.050000     10.000000
75%    1019.000000   3.000000   300.00000   0.100000     15.000000
max    1025.000000   5.000000  1200.00000   0.150000     50.000000

In [38]:
df.shape

(25, 10)

In [40]:
df.columns

Index(['OrderID', 'OrderDate', 'Region', 'Product', 'Quantity', 'UnitPrice',
       'CustomerSegment', 'Discount', 'ShippingCost', 'DeliveryDate'],
      dtype='object')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          25 non-null     int64
 1   OrderDate        25 non-null     object
 2   Region           25 non-null     object
 3   Product          25 non-null     object
 4   Quantity         25 non-null     int64
 5   UnitPrice        25 non-null     float64
 6   CustomerSegment  25 non-null     object
 7   Discount         25 non-null     float64
 8   ShippingCost     25 non-null     float64
 9   DeliveryDate     23 non-null     object
dtypes: float64(3), int64(2), object(5)
memory usage: 2.1+ KB

In [42]:
df.isna().sum()

OrderID            0
OrderDate          0
Region             0
Product            0
Quantity           0
UnitPrice          0
CustomerSegment    0
Discount           0
ShippingCost       0
DeliveryDate       2
dtype: int64

In [43]:
df['DeliveryDate'] = df['DeliveryDate'].ffill()

In [44]:
df.isna().sum()

OrderID            0
OrderDate          0
Region             0
Product            0
Quantity           0
UnitPrice          0
CustomerSegment    0
Discount           0
ShippingCost       0
DeliveryDate       0
dtype: int64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          25 non-null     int64
 1   OrderDate        25 non-null     object
 2   Region           25 non-null     object
 3   Product          25 non-null     object
 4   Quantity         25 non-null     int64
 5   UnitPrice        25 non-null     float64
 6   CustomerSegment  25 non-null     object
 7   Discount         25 non-null     float64
 8   ShippingCost     25 non-null     float64
 9   DeliveryDate     25 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 2.1+ KB

In [48]:
df['DeliveryDate'] = pd.to_datetime(df['DeliveryDate'])

In [65]:
df.sample()

,OrderID,OrderDate,Region,Product,Quantity,UnitPrice,CustomerSegment,Discount,ShippingCost,DeliveryDate,year,month,monthname,day,dayname,week
18,1019,2023-01-23,East,Monitor,2,300.0,Consumer,0.05,30.0,2023-01-26,2023,1,January,26,Thursday,3

In [ ]:
# df['week'] = df['DeliveryDate'].dt.weekday
# df['dayname'] = df['DeliveryDate'].dt.day_name()
# df['day'] = df['DeliveryDate'].dt.day
# df['monthname'] = df['DeliveryDate'].dt.month_name()
# df['month'] = df['DeliveryDate'].dt.month
# df['year'] = df['DeliveryDate'].dt.year